export enum Icons {
  ARROW_BACK = 'arrow_back',
  ARROW_FORWARD = 'arrow_forward',
  ATTACH_FILE = 'attach_file',
  CHEVRON_LEFT = 'chevron_left',
  CHEVRON_RIGHT = 'chevron_right',
  CLOSE = 'close',
  DELETE = 'delete',
  DIRECTIONS = 'directions',
  EDIT = 'edit',
  HOME = 'home',
  LOCATION_ON = 'location_on',
  MAP = 'map',
  MENU = 'menu',
  MORE = 'more_vert',
  MOVING = 'moving',
  NORTH_WEST = 'north_west',
  ROUTE = 'route',
  SETTINGS = 'settings',
}
